<?php

namespace Javicode\SharingExpensesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SharingGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharingGroupRepository extends EntityRepository
{
}
